decisionadvisor/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

decisionadvisor/decisionadvisor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assets/', include('management.assets_liabilities.urls')),
    path('inventory/', include('supplychain.inventory.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('management/', include('management.humanresource.urls')),
    path('agent/', include('supplychain.suppliers_customers.urls')),

]

decisionadvisor/management/assets_liabilities/urls.py
from django.urls import path
from . import views

app_name='assets'
urlpatterns = [
    path('new/', views.CreateAssetsView.as_view(), name='assets_new'),
    path('detail/<int:pk>/', views.AssetsDetailView.as_view(), name='assets_detail'),
    path('', views.AssetsListView.as_view(), name='assets_list'),
    path('update/<int:pk>/', views.AssetsUpdateView.as_view(), name='assets_update'),
    path('delete/<int:pk>/', views.AssetsDeleteView.as_view(), name='assets_delete'),
    
    #######################################################################################
    path('liabilities/new/', views.CreateLiabilitiesView.as_view(), name='liabilities_new'),
    path('liabilities/detail/<int:pk>/', views.LiabilitiesDetailView.as_view(), name='liabilities_detail'),
    path('liabilities/', views.LiabilitiesListView.as_view(), name='liabilities_list'),
    path('liabilities/update/<int:pk>/', views.LiabilitiesUpdateView.as_view(), name='liabilities_update'),
    path('liabilities/delete/<int:pk>/', views.LiabilitiesDeleteView.as_view(), name='liabilities_delete'),

]

decisionadvisor/management/humanresource/urls.py
from django.urls import path
from . import views

app_name = 'HR'

urlpatterns = [
    ######################################################################################################
    path('departments/', views.DepartmentsListView.as_view(), name='departments_list'),
    path('departments/new/', views.DepartmentsCreateView.as_view(), name='departments_new'),
    path('departments/detail/<int:pk>/', views.DepartmentsDetailView.as_view(), name='departments_detail'),
    path('departments/update/<int:pk>/', views.DepartmentsUpdateView.as_view(), name='departments_update'),
    path('departments/delete/<int:pk>/', views.DepartmentsDeleteView.as_view(), name='departments_delete'),
    ##############################################################################################################3
    path('employees/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employee/new/', views.EmployeeCreateView.as_view(), name='employee_new'),
    path('employee/detail/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee/update/<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', views.EmployeeDeleteView.as_view(), name='employee_delete'),
    ##########################################################################################################
    path('salaries/', views.SalariesListView.as_view(), name='salaries_list'),
    path('salaries/new/', views.SalariesCreateView.as_view(), name='salaries_new'),
    path('salaries/detail/<int:pk>/', views.SalariesDetailView.as_view(), name='salaries_detail'),
    path('salaries/update/<int:pk>/', views.SalariesUpdateView.as_view(), name='salaries_update'),
    path('salaries/delete/<int:pk>/', views.SalariesDeleteView.as_view(), name='salaries_delete'),
    ##########################################################################################################
    path('titles/', views.TitlesListView.as_view(), name='titles_list'),
    path('titles/new/', views.TitlesCreateView.as_view(), name='titles_new'),
    path('titles/detail/<int:pk>/', views.TitlesDetailView.as_view(), name='titles_detail'),
    path('titles/update/<int:pk>/', views.TitlesUpdateView.as_view(), name='titles_update'),
    path('titles/delete/<int:pk>/', views.TitlesDeleteView.as_view(), name='titles_delete'),
    ##########################################################################################################
    path('deptmanager/', views.DeptManagerListView.as_view(), name='dept_manager_list'),
    path('deptmanager/new/', views.DeptManagerCreateView.as_view(), name='dept_manager_new'),
    path('deptmanager/detail/<int:pk>/', views.DeptManagerDetailView.as_view(), name='dept_manager_detail'),
    path('deptmanager/update/<int:pk>/', views.DeptManagerUpdateView.as_view(), name='dept_manager_update'),
    path('deptmanager/delete/<int:pk>/', views.DeptManagerDeleteView.as_view(), name='dept_manager_delete'),
    ##########################################################################################################
    path('deptemployee/', views.DeptEmployeeListView.as_view(), name='dept_employee_list'),
    path('deptemployee/new/', views.DeptEmployeeCreateView.as_view(), name='dept_employee_new'),
    path('deptemployee/detail/<int:pk>/', views.DeptEmployeeDetailView.as_view(), name='dept_employee_detail'),
    path('deptemployee/update/<int:pk>/', views.DeptEmployeeUpdateView.as_view(), name='dept_employee_update'),
    path('deptemployee/delete/<int:pk>/', views.DeptEmployeeDeleteView.as_view(), name='dept_employee_delete'),
    ##########################################################################################################
    
]

decisionadvisor/supplychain/inventory/urls.py
from django.urls import path
from . import views

app_name='products'
urlpatterns = [
    path('product/new/', views.CreateProductView.as_view(), name='product_new'),
    path('product/detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('product/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('account/new/', views.CreateAccountView.as_view(), name='account_new'),
    path('account/detail/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
    path('account/', views.AccountListView.as_view(), name='account_list'),
    path('account/update/<int:pk>/', views.AccountUpdateView.as_view(), name='account_update'),
    path('account/delete/<int:pk>/', views.AccountDeleteView.as_view(), name='account_delete'),
]

decisionadvisor/templates/_navigation.html
<nav class="navbar fixed-top navbar-expand-lg bg-light mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="#">Decision Advisor</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          
            {% comment %} <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> Products </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'assets:product_new' %}">New</a>
                <a class="dropdown-item" href="{% url 'products:product_list' %}">All</a>
              </div> {% endcomment %}

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> Employees </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'HR:employee_new' %}">New</a>
                <a class="dropdown-item" href="{% url 'HR:employee_list' %}">All</a>
              </div>
              
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> Salaries </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'HR:salaries_new' %}">New</a>
                <a class="dropdown-item" href="{% url 'HR:salaries_list' %}">All</a>
              </div>
              
            </li>
              <a class="nav-item nav-link" href="{% url 'HR:departments_list' %}" class="btn btn-simple"> Departments </a>

            <li>
              <a class="nav-item nav-link" href="{% url 'HR:titles_list' %}" class="btn btn-simple"> Titles </a>

            </li>
            <li>
              <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple"><i class="fas fa-sign-out-alt"></i> Log out</a>

            </li>
            <li>
            </li>
            <li>
            </li>



          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}?next={{request.path}}" class="btn btn-simple"><i class="fas fa-user"></i> Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}?next={{request.path}}" class="btn btn-simple"><i class="fas fa-user-plus"></i> Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

decisionadvisor/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>


  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    
    <!-- Bootstrap minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- JS, Popper.js, and jQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Fontawesome icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  </head>
  <body>
    <div class="container mb-5">
      {% include "_navigation.html" %}
    </div>

    <div class="container pt-4 mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

  </body>
</html>