decisionadvisor/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

decisionadvisor/decisionadvisor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assets/', include('management.assets_liabilities.urls')),
    path('inventory/', include('supplychain.inventory.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('management/', include('management.humanresource.urls')),
    path('agent/', include('supplychain.suppliers_customers.urls')),

]

decisionadvisor/supplychain/suppliers_customers/urls.py
from django.urls import path
from . import views

app_name = 'suppliers_customers'

urlpatterns = [
    ##############################################################################################################3
    path('suppliers/', views.SupplierListView.as_view(), name='supplier_list'),
    path('supplier/new/', views.SupplierCreateView.as_view(), name='supplier_new'),
    path('supplier/detail/<int:pk>/', views.SupplierDetailView.as_view(), name='supplier_detail'),
    path('supplier/update/<int:pk>/', views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('supplier/delete/<int:pk>/', views.SupplierDeleteView.as_view(), name='supplier_delete'),
    
    ##########################################################################################################
    path('customers/', views.CustomerListView.as_view(), name='customer_list'),
    path('customer/new/', views.CustomerCreateView.as_view(), name='customer_new'),
    path('customer/detail/<int:pk>/', views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/update/<int:pk>/', views.CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='customer_delete'),
]

decisionadvisor/supplychain/suppliers_customers/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Suppliers(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    sup_no = models.AutoField(primary_key=True, null=False)
    name = models.CharField(max_length=100)
    balance = models.IntegerField(null=True,)
    email = models.EmailField(max_length=254,null=True)
    phone = models.PositiveIntegerField(null=True)


    class Meta:
        db_table = 'suppliers'
        ordering = ['name']

    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("suppliers_customers:supplier_detail", kwargs={"pk": self.pk})




    #VSCode will see the objects declared
    objects = models.Manager


class Customers(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    cus_no = models.AutoField(primary_key=True, null=False)
    first_name = models.CharField(max_length=14)
    last_name = models.CharField(max_length=16, null=True) 
    ID = models.PositiveIntegerField(null = True)
    gender = models.CharField(max_length=1, null=True, choices=GENDER_CHOICES)
    balance = models.IntegerField(null=True)
    email = models.EmailField(max_length=254,null=True)
    phone = models.PositiveIntegerField(null=True)

    class Meta:
        db_table = 'customers'
        ordering = ['first_name']

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("suppliers_customers:customer_detail", kwargs={"pk": self.pk})

    def fullname(self):
        return self.first_name + ' ' + self.last_name


    #VSCode will see the objects declared
    objects = models.Manager()

decisionadvisor/supplychain/suppliers_customers/forms.py
from django import forms 
from .models import Customers, Suppliers

class SupplierForm(forms.ModelForm):

    class Meta():
        model=Suppliers
        fields = '__all__'
       

class CustomerForm(forms.ModelForm):

    class Meta():
        model=Customers
        fields = '__all__'
        

decisionadvisor/supplychain/suppliers_customers/views.py
from django.shortcuts import render
from .models import Customers, Suppliers
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DetailView,
                                    UpdateView, DeleteView,
                                    ListView )
from .forms import (CustomerForm, SupplierForm)


# Create your views here.

#Suppliers views
class SupplierCreateView(LoginRequiredMixin, CreateView):
    model = Suppliers
    form_class = SupplierForm

class SupplierDetailView(LoginRequiredMixin, DetailView):
    model = Suppliers

class SupplierUpdateView(LoginRequiredMixin, UpdateView):
    model = Suppliers
    form_class = SupplierForm
    template_name_suffix = '_update_form'


class SupplierDeleteView(LoginRequiredMixin, DeleteView):
    model = Suppliers
    success_url = reverse_lazy('suppliers_customers:supplier_list')

class SupplierListView(LoginRequiredMixin, ListView):
    model = Suppliers

#######################################################################################
class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customers
    form_class = CustomerForm

class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customers

class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Customers
    form_class = CustomerForm
    template_name_suffix = '_update_form'


class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customers
    success_url = reverse_lazy('suppliers_customers:customer_list')

class CustomerListView(LoginRequiredMixin, ListView):
    model = Customers

#######################################################################################

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/customers_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/customers_detail.html
{% extends "base.html" %}
{% block content %}

<h3>Name {{customers.fullname}} </h3>
<p> ID: {{customers.ID}} </p>
<p> Gender : {{customers.gender}}</p>
<p> Email: {{customers.email}} </p>
<p> Phone: {{customers.phone}} </p>
<p> Balance: {{customers.balance}} </p>

{% comment %} <p> Title: 
  {% for title in customer.title.all %}

   {{title.title}},
  
  {% endfor %}
</p> {% endcomment %}


{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'suppliers_customers:customer_update' pk=customers.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'suppliers_customers:customer_delete' pk=customers.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/customers_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Customer</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Add Customer">
  </form>
</div>

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/customers_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Customers</h2>

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>ID</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Balance</th>
                </tr>
            </thead>
    {% for customer in customer_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'suppliers_customers:customer_detail' pk=customer.pk %}">{{customer.fullname}}</a></td>
                    <td>{{customer.gender}}</td>
                    <td>{{customer.ID}}</td>
                    <td>{{customer.phone}}</td>
                    <td>{{customer.email}}</td>
                    <td>{{customer.balance}}</td>
                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/customers_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Customer</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Customer">
  </form>
</div>

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/suppliers_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/suppliers_detail.html
{% extends "base.html" %}
{% block content %}

<h3>Name {{suppliers.fullname}} </h3>
<p> Email: {{suppliers.email}} </p>
<p> Phone: {{suppliers.phone}} </p>
<p> Balance: {{suppliers.balance}} </p>

{% comment %} <p> Title: 
  {% for title in supplier.title.all %}

   {{title.title}},
  
  {% endfor %}
</p> {% endcomment %}


{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'suppliers_customers:supplier_update' pk=suppliers.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'suppliers_customers:supplier_delete' pk=suppliers.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/suppliers_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Supplier</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Add Supplier">
  </form>
</div>

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/suppliers_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Suppliers</h2>

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Balance</th>
                </tr>
            </thead>
    {% for supplier in supplier_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'suppliers_customers:supplier_detail' pk=supplier.pk %}">{{supplier.fullname}}</a></td>
                    <td>{{supplier.email}}</td>
                    <td>{{supplier.phone}}</td>
                    <td>{{supplier.balance}}</td>
                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

decisionadvisor/supplychain/suppliers_customers/templates/suppliers_customers/suppliers_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Supplier</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Supplier">
  </form>
</div>

{% endblock content %}