decisionadvisor/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

decisionadvisor/decisionadvisor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assets/', include('management.assets_liabilities.urls')),
    path('inventory/', include('supplychain.inventory.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('management/', include('management.humanresource.urls')),
    path('agent/', include('supplychain.suppliers_customers.urls')),

]

decisionadvisor/supplychain/inventory/urls.py
from django.urls import path
from . import views

app_name='products'
urlpatterns = [
    path('product/new/', views.CreateProductView.as_view(), name='product_new'),
    path('product/detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('product/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('account/new/', views.CreateAccountView.as_view(), name='account_new'),
    path('account/detail/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
    path('account/', views.AccountListView.as_view(), name='account_list'),
    path('account/update/<int:pk>/', views.AccountUpdateView.as_view(), name='account_update'),
    path('account/delete/<int:pk>/', views.AccountDeleteView.as_view(), name='account_delete'),
]

decisionadvisor/accounts/models.py
from django.db import models
from django.contrib import auth
from django.urls import reverse

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}", format(self.username)

decisionadvisor/supplychain/inventory/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
import misaka

class Product(models.Model):
    
    name = models.CharField(max_length=255, unique=True)
    quantity = models.PositiveIntegerField()
    b_price = models.PositiveIntegerField()
    description = models.CharField(max_length=255, blank=True)
    s_price = models.PositiveIntegerField(null=True, blank=True)
    expenses = models.PositiveIntegerField(null=True, blank=True)	

    

    def __str__(self):
        return self.name

    def unit_bp(self):
        return (self.b_price + self.expenses)/self.quantity
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']

    #VSCode will see the objects declared
    objects = models.Manager()




# class Transaction(models.Model):



# statement of financial Position
class Accounts(models.Model):
    ACCOUNT_CHOICES = (
        ('ASSET','Asset'),
        ('LIABILITY','Liability'),
        ('CAPITAL','Capital'),
        ('EXPENSE', 'Expense'),
    )
    account_no = models.AutoField(primary_key=True,)
    name = models.CharField(max_length=20,)
    amount = models.IntegerField()
    account_type = models.CharField(max_length=10, null=True, choices=ACCOUNT_CHOICES)
    description = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:account_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']

    #VSCode will see the objects declared
    objects = models.Manager()

class Transactions(models.Model):
    ACCOUNT_CHOICES = (
        ('DR','Debit'),
        ('CR','Credit')        
    )
    id = models.AutoField(primarykey=True)
    date = models.DateTimeField(auto_now_add=True, null=False)
    product = models.ForeignKey(Product, related_name='transactions', on_delete=models.DO_NOTHING)
    quantity = models.PositiveIntegerField()
    details = models.CharField(max_length=200, null=True, blank=True)
    account = models.CharField(max_length=4, choices=ACCOUNT_CHOICES)

    def __str__(self):
        return self.date
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:transaction_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']

    #VSCode will see the objects declared
    objects = models.Manager()

decisionadvisor/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label='Display Name'
        self.fields['email'].label='Email Address'

        

decisionadvisor/supplychain/inventory/forms.py
from django import forms
from .models import Product, Accounts, Transactions

class ProductForm(forms.ModelForm):

    class Meta():
        model = Product
        fields = '__all__'
        labels = {
        "s_price": "Prospective Unit Price",
        'b_price': 'Buying Price',
        }

class AccountForm(forms.ModelForm):

    class Meta():
        model = Accounts
        fields = '__all__'
        

class TransactionForm(forms.ModelForm):

    class Meta():
        model = Accounts
        fields = '__all__'

decisionadvisor/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

decisionadvisor/supplychain/inventory/views.py
from .forms import ProductForm, AccountForm
from .models import Product, Accounts
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
class CreateProductView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'inventory/product_detail.html'
    form_class = ProductForm
    model = Product

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'inventory/product_detail.html'
    template_name_suffix = '_update_form'
    form_class = ProductForm
    model = Product


class ProductDetailView(DetailView):
    model = Product

class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        return Product.objects.order_by('name')

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Product
    success_url = reverse_lazy('products:product_list')

###############################################

class CreateAccountView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'inventory/account_detail.html'
    form_class = AccountForm
    model = Accounts

class AccountUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'inventory/account_detail.html'
    template_name_suffix = '_update_form'
    form_class = AccountForm
    model = Accounts


class AccountDetailView(DetailView):
    model = Accounts
    

class AccountListView(ListView):
    model = Accounts

    

class AccountDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Accounts
    success_url = reverse_lazy('products:account_list')

decisionadvisor/supplychain/inventory/templates/inventory/accounts_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/accounts_detail.html
{% extends "base.html" %}
{% block content %}

<h3> {{accounts.name}} </h3>
<p> Price: {{accounts.balance}}</p>
<p> Type: {{accounts.account_type}}

{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'products:account_update' pk=accounts.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'products:account_delete' pk=accounts.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/accounts_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Account</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Add Account">
  </form>
</div>

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/accounts_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Accounts</h2>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Type</th>
                </tr>
            </thead>
    {% for account in accounts_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'products:account_detail' pk=account.pk %}">{{account.name}}</a></td>
                    <td>{{account.amount}}</td>
                    {% if account.account_type == 'AS'%}
                    <td>Asset</td>

                    {%elif account.account_type == 'LI' %}
                    <td>Liability</td>

                    {%elif account.account_type == 'CA' %}
                    <td>Capital</td>

                    {%elif account.account_type == 'EX' %}
                    <td>Expense</td>

                    {% endif %}


                    
                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/accounts_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1> Update Account</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Account">
  </form>
</div>

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/product_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/product_detail.html
{% extends "base.html" %}
{% block content %}

<h3> {{product.name}} </h3>
<p> Price: {{product.price}}</p>
<p> In Stock: {{product.quantity}}

{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'products:product_update' pk=product.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'products:product_delete' pk=product.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/product_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new product</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="New product">
  </form>
</div>

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/product_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Products</h2>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
    {% for product in product_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'products:product_detail' pk=product.pk %}">{{product.name}}</a></td>
                    <td>{{product.b_price}}</td>
                    <td>{{product.quantity}}</td>
                    
                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

decisionadvisor/supplychain/inventory/templates/inventory/product_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update product</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Product">
  </form>
</div>

{% endblock content %}