decisionadvisor/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

decisionadvisor/decisionadvisor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assets/', include('management.assets_liabilities.urls')),
    path('inventory/', include('supplychain.inventory.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('management/', include('management.humanresource.urls')),
    path('agent/', include('supplychain.suppliers_customers.urls')),

]

decisionadvisor/management/assets_liabilities/urls.py
from django.urls import path
from . import views

app_name='assets'
urlpatterns = [
    path('new/', views.CreateAssetsView.as_view(), name='assets_new'),
    path('detail/<int:pk>/', views.AssetsDetailView.as_view(), name='assets_detail'),
    path('', views.AssetsListView.as_view(), name='assets_list'),
    path('update/<int:pk>/', views.AssetsUpdateView.as_view(), name='assets_update'),
    path('delete/<int:pk>/', views.AssetsDeleteView.as_view(), name='assets_delete'),
    
    #######################################################################################
    path('liabilities/new/', views.CreateLiabilitiesView.as_view(), name='liabilities_new'),
    path('liabilities/detail/<int:pk>/', views.LiabilitiesDetailView.as_view(), name='liabilities_detail'),
    path('liabilities/', views.LiabilitiesListView.as_view(), name='liabilities_list'),
    path('liabilities/update/<int:pk>/', views.LiabilitiesUpdateView.as_view(), name='liabilities_update'),
    path('liabilities/delete/<int:pk>/', views.LiabilitiesDeleteView.as_view(), name='liabilities_delete'),

]

decisionadvisor/management/assets_liabilities/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify



# Create your models here.
class Assets(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, unique=True)
    value = models.PositiveIntegerField()	
    purchase_date = models.DateField(null=True)
    description = models.CharField(max_length=255)
    

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('assets:assets_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']

    #VSCode will see the objects declared
    objects = models.Manager()

class Liabilities(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, unique=True)
    amount = models.PositiveIntegerField()	
    due_date = models.DateField(null=True)
    description = models.CharField(max_length=255, null=True)


    

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('assets:assets_products_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']
    
    #VSCode will see the objects declared
    objects = models.Manager()

decisionadvisor/management/assets_liabilities/forms.py
from django import forms
from .models import Assets, Liabilities

class AssetsForm(forms.ModelForm):

    class Meta():
        model = Assets
        fields = '__all__'
        widgets = {
            'purchase_date':forms.DateInput(attrs={'type': 'date'}),

        }

class LiabilitiesForm(forms.ModelForm):

    class Meta():
        model = Liabilities
        fields = '__all__'
        widgets = {
            'due_date':forms.DateInput(attrs={'type': 'date'}),
        }
        

decisionadvisor/management/assets_liabilities/views.py
from .forms import AssetsForm, LiabilitiesForm
from .models import Assets, Liabilities
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
class CreateAssetsView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'assets/assets_detail.html'
    form_class = AssetsForm
    model = Assets

class AssetsUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'assets/assets_detail.html'
    template_name_suffix = '_update_form'
    form_class = AssetsForm
    model = Assets



class AssetsDetailView(DetailView):
    model = Assets

class AssetsListView(ListView):
    model = Assets

    def get_queryset(self):
        return Assets.objects.order_by('name')

class AssetsDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Assets
    success_url = reverse_lazy('assets:assets_list')



# Create your views here.
class CreateLiabilitiesView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'assets/liabilities_detail.html'
    form_class = LiabilitiesForm
    model = Liabilities

class LiabilitiesUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'assets/liabilities_detail.html'
    template_name_suffix = '_update_form'
    form_class = LiabilitiesForm
    model = Liabilities



class LiabilitiesDetailView(DetailView):
    model = Liabilities

class LiabilitiesListView(ListView):
    model = Liabilities

    def get_queryset(self):
        return Liabilities.objects.order_by('name')

class LiabilitiesDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Liabilities
    success_url = reverse_lazy('assets:liabilities_list')

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/assets_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/assets_detail.html
{% extends "base.html" %}
{% block content %}

<h3> {{assets.name}} </h3>
<p> Value: {{assets.value}}</p>
<p> PurchaseDate: {{assets.purchase_date}} </p>
<p> Description: {{assets.description}}

{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'assets:assets_update' pk=assets.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'assets:assets_delete' pk=assets.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/assets_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Asset</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Add Asset">
  </form>
</div>

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/assets_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Assets</h2>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                    <th>PurchaseDate</th>
                    <th>Description</th>

                </tr>
            </thead>
    {% for asset in assets_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'assets:assets_detail' pk=asset.pk %}">{{asset.name}}</a></td>
                    <td>{{asset.value}}</td>
                    <td>{{asset.purchase_date}}</td>
                    <td>{{asset.description}}</td>

                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/assets_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update asset</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update asset">
  </form>
</div>

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/liabilities_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/liabilities_detail.html
{% extends "base.html" %}
{% block content %}

<h3> {{liabilities.name}} </h3>
<p> Amount: {{liabilities.amount}}</p>
<p> Due Date: {{liabilities.due_date}} </p>
<p> Description: {{liabilities.description}}

{% if user.is_authenticated %}
  <a class='btn btn-secondary' href="{% url 'liabilities:liabilities_update' pk=liabilities.pk %}">
    <span class='fas fa-pen'></span>
    <span class="text-body icon-label">Edit</span>
  </a>
  <a class='btn btn-secondary' href="{% url 'liabilities:liabilities_delete' pk=liabilities.pk %}">
    <i class="fas fa-trash"></i>
    <span class="text-body icon-label">Delete</span>

  </a>
{% endif %}

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/liabilities_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Add new Liability</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Add Liability">
  </form>
</div>

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/liabilities_list.html
{% extends "base.html" %}
{% block content %}


<div class="container">
    <h2>Liabilities</h2>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Due Date</th>
                    <th>Description</th>

                </tr>
            </thead>
    {% for liability in liabilities_list %}
            <tbody>
                <tr>
                    <td><a href = "{% url 'assets:liabilities_detail' pk=liability.pk %}">{{liability.name}}</a></td>
                    <td>{{liability.amount}}</td> 
                    <td>{{liability.due_date}}</td>
                    <td>{{liability.description}}</td>
                    <!--TODO find out how to use comma when displaying  -->  
                </tr>
            </tbody>

    {% endfor%}
        </table>
</div>

{% endblock content %}

decisionadvisor/management/assets_liabilities/templates/assets_liabilities/liabilities_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Update Liability</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update Liability">
  </form>
</div>

{% endblock content %}